# Generated by Django 5.2.1 on 2025-05-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名')),
                ('category', models.CharField(max_length=50, verbose_name='カテゴリ')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='メーカー')),
                ('color', models.CharField(max_length=30, verbose_name='色(カラー)')),
                ('position', models.CharField(max_length=30, verbose_name='ポジション(グローブのみ)')),
                ('description', models.TextField(verbose_name='説明')),
                ('image', models.ImageField(upload_to='item_images', verbose_name='画像')),
                ('price', models.PositiveBigIntegerField(verbose_name='金額')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='スラッグ')),
            ],
        ),
    ]
