# Generated by Django 5.2.1 on 2025-05-23 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_delete_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品一覧'},
        ),
    ]
