# Generated by Django 5.2.1 on 2025-05-29 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, verbose_name='名前'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='郵便番号')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='国名')),
                ('prefecture', models.CharField(blank=True, max_length=50, null=True, verbose_name='都道府県')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='市区町村')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='番地以下')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
