# Generated by Django 5.2.1 on 2025-07-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_address_created_at_alter_address_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(fields=('user', 'postal_code', 'country', 'prefecture', 'city', 'street'), name='unique_user_address'),
        ),
    ]
