# Generated by Django 5.2.1 on 2025-05-23 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_total_price_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
