# Generated by Django 5.2.1 on 2025-05-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='item_images')),
                ('price', models.PositiveBigIntegerField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
