# Generated by Django 5.2.1 on 2025-05-22 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=50, verbose_name='カテゴリ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(max_length=30, verbose_name='色(カラー)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='item_images', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='item',
            name='manufacturer',
            field=models.CharField(max_length=50, verbose_name='メーカー'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='item',
            name='position',
            field=models.CharField(max_length=30, verbose_name='ポジション(グローブのみ)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.PositiveBigIntegerField(verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='スラッグ'),
        ),
    ]
